//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENRLReconSystem.WebAPI.srvAEOutOfAreaOption {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class pingHop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string classNameField;
        
        private string bundleNameField;
        
        private string bundleVersionField;
        
        private string bundleIdField;
        
        private string timestampField;
        
        private string applicationAuthorizedField;
        
        private keyValuePair[] configurationInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
                this.RaisePropertyChanged("className");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string bundleName {
            get {
                return this.bundleNameField;
            }
            set {
                this.bundleNameField = value;
                this.RaisePropertyChanged("bundleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string bundleVersion {
            get {
                return this.bundleVersionField;
            }
            set {
                this.bundleVersionField = value;
                this.RaisePropertyChanged("bundleVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string bundleId {
            get {
                return this.bundleIdField;
            }
            set {
                this.bundleIdField = value;
                this.RaisePropertyChanged("bundleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string applicationAuthorized {
            get {
                return this.applicationAuthorizedField;
            }
            set {
                this.applicationAuthorizedField = value;
                this.RaisePropertyChanged("applicationAuthorized");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("configurationInformation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public keyValuePair[] configurationInformation {
            get {
                return this.configurationInformationField;
            }
            set {
                this.configurationInformationField = value;
                this.RaisePropertyChanged("configurationInformation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class keyValuePair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1")]
    public partial class messageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class vr1StatusContainer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vr1_status_additional_infoField;
        
        private string vr1_status_codeField;
        
        private string vr1_status_code_descField;
        
        private string vr1_status_code_type_descField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string vr1_status_additional_info {
            get {
                return this.vr1_status_additional_infoField;
            }
            set {
                this.vr1_status_additional_infoField = value;
                this.RaisePropertyChanged("vr1_status_additional_info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vr1_status_code {
            get {
                return this.vr1_status_codeField;
            }
            set {
                this.vr1_status_codeField = value;
                this.RaisePropertyChanged("vr1_status_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string vr1_status_code_desc {
            get {
                return this.vr1_status_code_descField;
            }
            set {
                this.vr1_status_code_descField = value;
                this.RaisePropertyChanged("vr1_status_code_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string vr1_status_code_type_desc {
            get {
                return this.vr1_status_code_type_descField;
            }
            set {
                this.vr1_status_code_type_descField = value;
                this.RaisePropertyChanged("vr1_status_code_type_desc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class vrcStatusGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private vr1StatusContainer[] statusContainerBeansField;
        
        private string vr1_status_container_num_occField;
        
        private string vrc_status_generated_byField;
        
        private string vrc_status_orig_channelField;
        
        private string vrc_status_owned_byField;
        
        private string vrc_status_service_nameField;
        
        private string vrc_status_service_versionField;
        
        private string vrc_status_systemField;
        
        private string vrc_status_transidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("statusContainerBeans", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public vr1StatusContainer[] statusContainerBeans {
            get {
                return this.statusContainerBeansField;
            }
            set {
                this.statusContainerBeansField = value;
                this.RaisePropertyChanged("statusContainerBeans");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vr1_status_container_num_occ {
            get {
                return this.vr1_status_container_num_occField;
            }
            set {
                this.vr1_status_container_num_occField = value;
                this.RaisePropertyChanged("vr1_status_container_num_occ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string vrc_status_generated_by {
            get {
                return this.vrc_status_generated_byField;
            }
            set {
                this.vrc_status_generated_byField = value;
                this.RaisePropertyChanged("vrc_status_generated_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string vrc_status_orig_channel {
            get {
                return this.vrc_status_orig_channelField;
            }
            set {
                this.vrc_status_orig_channelField = value;
                this.RaisePropertyChanged("vrc_status_orig_channel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string vrc_status_owned_by {
            get {
                return this.vrc_status_owned_byField;
            }
            set {
                this.vrc_status_owned_byField = value;
                this.RaisePropertyChanged("vrc_status_owned_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string vrc_status_service_name {
            get {
                return this.vrc_status_service_nameField;
            }
            set {
                this.vrc_status_service_nameField = value;
                this.RaisePropertyChanged("vrc_status_service_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string vrc_status_service_version {
            get {
                return this.vrc_status_service_versionField;
            }
            set {
                this.vrc_status_service_versionField = value;
                this.RaisePropertyChanged("vrc_status_service_version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string vrc_status_system {
            get {
                return this.vrc_status_systemField;
            }
            set {
                this.vrc_status_systemField = value;
                this.RaisePropertyChanged("vrc_status_system");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string vrc_status_transid {
            get {
                return this.vrc_status_transidField;
            }
            set {
                this.vrc_status_transidField = value;
                this.RaisePropertyChanged("vrc_status_transid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class statusMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private statusMessageLevel statusMessageLevelField;
        
        private string messageTypeField;
        
        private string statusMessage1Field;
        
        private string hopLocationField;
        
        private string stackTraceField;
        
        private string statusOriginField;
        
        private vrcStatusGroup vrcStatusGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public statusMessageLevel statusMessageLevel {
            get {
                return this.statusMessageLevelField;
            }
            set {
                this.statusMessageLevelField = value;
                this.RaisePropertyChanged("statusMessageLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string messageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("messageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("statusMessage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusMessage1 {
            get {
                return this.statusMessage1Field;
            }
            set {
                this.statusMessage1Field = value;
                this.RaisePropertyChanged("statusMessage1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string hopLocation {
            get {
                return this.hopLocationField;
            }
            set {
                this.hopLocationField = value;
                this.RaisePropertyChanged("hopLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string statusOrigin {
            get {
                return this.statusOriginField;
            }
            set {
                this.statusOriginField = value;
                this.RaisePropertyChanged("statusOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public vrcStatusGroup vrcStatusGroup {
            get {
                return this.vrcStatusGroupField;
            }
            set {
                this.vrcStatusGroupField = value;
                this.RaisePropertyChanged("vrcStatusGroup");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public enum statusMessageLevel {
        
        /// <remarks/>
        INFORMATIONAL,
        
        /// <remarks/>
        FAULT,
        
        /// <remarks/>
        EXCEPTION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class serviceHop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bundleNameField;
        
        private string bundleVersionField;
        
        private string bundleIdField;
        
        private string startTimestampField;
        
        private string endTimestampField;
        
        private string totalTimeInMillisecondsField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bundleName {
            get {
                return this.bundleNameField;
            }
            set {
                this.bundleNameField = value;
                this.RaisePropertyChanged("bundleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string bundleVersion {
            get {
                return this.bundleVersionField;
            }
            set {
                this.bundleVersionField = value;
                this.RaisePropertyChanged("bundleVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string bundleId {
            get {
                return this.bundleIdField;
            }
            set {
                this.bundleIdField = value;
                this.RaisePropertyChanged("bundleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string startTimestamp {
            get {
                return this.startTimestampField;
            }
            set {
                this.startTimestampField = value;
                this.RaisePropertyChanged("startTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string endTimestamp {
            get {
                return this.endTimestampField;
            }
            set {
                this.endTimestampField = value;
                this.RaisePropertyChanged("endTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string totalTimeInMilliseconds {
            get {
                return this.totalTimeInMillisecondsField;
            }
            set {
                this.totalTimeInMillisecondsField = value;
                this.RaisePropertyChanged("totalTimeInMilliseconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class responseHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceCallStatus serviceCallStatusField;
        
        private string externalIdField;
        
        private string serviceNameField;
        
        private string serviceVersionField;
        
        private logLevel logLevelField;
        
        private string upmEnvironmentField;
        
        private serviceHop[] serviceHopsField;
        
        private statusMessage[] statusMessagesField;
        
        private internalUse internalUseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public serviceCallStatus serviceCallStatus {
            get {
                return this.serviceCallStatusField;
            }
            set {
                this.serviceCallStatusField = value;
                this.RaisePropertyChanged("serviceCallStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string externalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
                this.RaisePropertyChanged("externalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("serviceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string serviceVersion {
            get {
                return this.serviceVersionField;
            }
            set {
                this.serviceVersionField = value;
                this.RaisePropertyChanged("serviceVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public logLevel logLevel {
            get {
                return this.logLevelField;
            }
            set {
                this.logLevelField = value;
                this.RaisePropertyChanged("logLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string upmEnvironment {
            get {
                return this.upmEnvironmentField;
            }
            set {
                this.upmEnvironmentField = value;
                this.RaisePropertyChanged("upmEnvironment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceHops", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public serviceHop[] serviceHops {
            get {
                return this.serviceHopsField;
            }
            set {
                this.serviceHopsField = value;
                this.RaisePropertyChanged("serviceHops");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("statusMessages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public statusMessage[] statusMessages {
            get {
                return this.statusMessagesField;
            }
            set {
                this.statusMessagesField = value;
                this.RaisePropertyChanged("statusMessages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public internalUse internalUse {
            get {
                return this.internalUseField;
            }
            set {
                this.internalUseField = value;
                this.RaisePropertyChanged("internalUse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public enum serviceCallStatus {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        INFO,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        EXCEPTION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public enum logLevel {
        
        /// <remarks/>
        DEFAULT,
        
        /// <remarks/>
        TRACE,
        
        /// <remarks/>
        DEBUG,
        
        /// <remarks/>
        INFO,
        
        /// <remarks/>
        WARN,
        
        /// <remarks/>
        ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class internalUse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uidField;
        
        private string serviceNameField;
        
        private string serviceVersionField;
        
        private string originalConsumerField;
        
        private string originalServiceNameField;
        
        private string originalServiceVersionField;
        
        private System.Nullable<int> logSequenceField;
        
        private string uidGeneratedByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("serviceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string serviceVersion {
            get {
                return this.serviceVersionField;
            }
            set {
                this.serviceVersionField = value;
                this.RaisePropertyChanged("serviceVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string originalConsumer {
            get {
                return this.originalConsumerField;
            }
            set {
                this.originalConsumerField = value;
                this.RaisePropertyChanged("originalConsumer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string originalServiceName {
            get {
                return this.originalServiceNameField;
            }
            set {
                this.originalServiceNameField = value;
                this.RaisePropertyChanged("originalServiceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string originalServiceVersion {
            get {
                return this.originalServiceVersionField;
            }
            set {
                this.originalServiceVersionField = value;
                this.RaisePropertyChanged("originalServiceVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<int> logSequence {
            get {
                return this.logSequenceField;
            }
            set {
                this.logSequenceField = value;
                this.RaisePropertyChanged("logSequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string uidGeneratedBy {
            get {
                return this.uidGeneratedByField;
            }
            set {
                this.uidGeneratedByField = value;
                this.RaisePropertyChanged("uidGeneratedBy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(pingResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(responseBase2))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(putOutOfAreaOptionResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public abstract partial class responseBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private responseHeader responseHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public responseHeader responseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
                this.RaisePropertyChanged("responseHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class pingResponse : responseBase {
        
        private pingHop[] pingHopsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pingHops", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public pingHop[] pingHops {
            get {
                return this.pingHopsField;
            }
            set {
                this.pingHopsField = value;
                this.RaisePropertyChanged("pingHops");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(putOutOfAreaOptionResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1")]
    public partial class responseBase2 : responseBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1")]
    public partial class putOutOfAreaOptionResponse : responseBase2 {
        
        private messageType[] outOfAreaOptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("messages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public messageType[] outOfAreaOption {
            get {
                return this.outOfAreaOptionField;
            }
            set {
                this.outOfAreaOptionField = value;
                this.RaisePropertyChanged("outOfAreaOption");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1")]
    public partial class gpsSystemParametersType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIdField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("clientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1")]
    public partial class controlModifiersType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gpsSystemParametersType gpsSystemParametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gpsSystemParametersType gpsSystemParameters {
            get {
                return this.gpsSystemParametersField;
            }
            set {
                this.gpsSystemParametersField = value;
                this.RaisePropertyChanged("gpsSystemParameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class requestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applicationNameField;
        
        private string applicationInstanceNameField;
        
        private logLevel logLevelField;
        
        private string externalIdField;
        
        private keyValuePair[] serviceOptionField;
        
        private internalUse internalUseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string applicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
                this.RaisePropertyChanged("applicationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string applicationInstanceName {
            get {
                return this.applicationInstanceNameField;
            }
            set {
                this.applicationInstanceNameField = value;
                this.RaisePropertyChanged("applicationInstanceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public logLevel logLevel {
            get {
                return this.logLevelField;
            }
            set {
                this.logLevelField = value;
                this.RaisePropertyChanged("logLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string externalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
                this.RaisePropertyChanged("externalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceOption", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public keyValuePair[] serviceOption {
            get {
                return this.serviceOptionField;
            }
            set {
                this.serviceOptionField = value;
                this.RaisePropertyChanged("serviceOption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public internalUse internalUse {
            get {
                return this.internalUseField;
            }
            set {
                this.internalUseField = value;
                this.RaisePropertyChanged("internalUse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(pingRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(putOutOfAreaOptionRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public abstract partial class requestBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private requestHeader requestHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public requestHeader requestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("requestHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class pingRequest : requestBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1")]
    public partial class putOutOfAreaOptionRequest : requestBase {
        
        private putOutOfAreaOptionRequestOutOfAreaOptionRequest outOfAreaOptionRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public putOutOfAreaOptionRequestOutOfAreaOptionRequest outOfAreaOptionRequest {
            get {
                return this.outOfAreaOptionRequestField;
            }
            set {
                this.outOfAreaOptionRequestField = value;
                this.RaisePropertyChanged("outOfAreaOptionRequest");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1")]
    public partial class putOutOfAreaOptionRequestOutOfAreaOptionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private controlModifiersType controlModifiersField;
        
        private string householdIdField;
        
        private string outOfAreaIndField;
        
        private string caseNumberField;
        
        private string outOfAreaDisenrollmentDateField;
        
        private string sendFulfillmentIndField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public controlModifiersType controlModifiers {
            get {
                return this.controlModifiersField;
            }
            set {
                this.controlModifiersField = value;
                this.RaisePropertyChanged("controlModifiers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string householdId {
            get {
                return this.householdIdField;
            }
            set {
                this.householdIdField = value;
                this.RaisePropertyChanged("householdId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string outOfAreaInd {
            get {
                return this.outOfAreaIndField;
            }
            set {
                this.outOfAreaIndField = value;
                this.RaisePropertyChanged("outOfAreaInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string caseNumber {
            get {
                return this.caseNumberField;
            }
            set {
                this.caseNumberField = value;
                this.RaisePropertyChanged("caseNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string outOfAreaDisenrollmentDate {
            get {
                return this.outOfAreaDisenrollmentDateField;
            }
            set {
                this.outOfAreaDisenrollmentDateField = value;
                this.RaisePropertyChanged("outOfAreaDisenrollmentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sendFulfillmentInd {
            get {
                return this.sendFulfillmentIndField;
            }
            set {
                this.sendFulfillmentIndField = value;
                this.RaisePropertyChanged("sendFulfillmentInd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1", ConfigurationName="srvAEOutOfAreaOption.PutOutofareaoption")]
    public interface PutOutofareaoption {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.ServiceException), Action="", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePingResponse invokePing(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePing request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePingResponse> invokePingAsync(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePing request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.ServiceException), Action="", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeServiceResponse invokeService(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeService request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeServiceResponse> invokeServiceAsync(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeService request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokePing", WrapperNamespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1", IsWrapped=true)]
    public partial class invokePing {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.pingRequest arg0;
        
        public invokePing() {
        }
        
        public invokePing(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.pingRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokePingResponse", WrapperNamespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1", IsWrapped=true)]
    public partial class invokePingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.pingResponse @return;
        
        public invokePingResponse() {
        }
        
        public invokePingResponse(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.pingResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokeService", WrapperNamespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1", IsWrapped=true)]
    public partial class invokeService {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.putOutOfAreaOptionRequest arg0;
        
        public invokeService() {
        }
        
        public invokeService(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.putOutOfAreaOptionRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokeServiceResponse", WrapperNamespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1", IsWrapped=true)]
    public partial class invokeServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://upm3.uhc.com/uhcmr/consumers/outofareaoption/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.putOutOfAreaOptionResponse @return;
        
        public invokeServiceResponse() {
        }
        
        public invokeServiceResponse(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.putOutOfAreaOptionResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PutOutofareaoptionChannel : ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.PutOutofareaoption, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PutOutofareaoptionClient : System.ServiceModel.ClientBase<ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.PutOutofareaoption>, ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.PutOutofareaoption {
        
        public PutOutofareaoptionClient() {
        }
        
        public PutOutofareaoptionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PutOutofareaoptionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PutOutofareaoptionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PutOutofareaoptionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePingResponse ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.PutOutofareaoption.invokePing(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePing request) {
            return base.Channel.invokePing(request);
        }
        
        public ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.pingResponse invokePing(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.pingRequest arg0) {
            ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePing inValue = new ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePing();
            inValue.arg0 = arg0;
            ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePingResponse retVal = ((ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.PutOutofareaoption)(this)).invokePing(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePingResponse> ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.PutOutofareaoption.invokePingAsync(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePing request) {
            return base.Channel.invokePingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePingResponse> invokePingAsync(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.pingRequest arg0) {
            ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePing inValue = new ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokePing();
            inValue.arg0 = arg0;
            return ((ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.PutOutofareaoption)(this)).invokePingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeServiceResponse ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.PutOutofareaoption.invokeService(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeService request) {
            return base.Channel.invokeService(request);
        }
        
        public ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.putOutOfAreaOptionResponse invokeService(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.putOutOfAreaOptionRequest arg0) {
            ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeService inValue = new ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeService();
            inValue.arg0 = arg0;
            ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeServiceResponse retVal = ((ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.PutOutofareaoption)(this)).invokeService(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeServiceResponse> ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.PutOutofareaoption.invokeServiceAsync(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeService request) {
            return base.Channel.invokeServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeServiceResponse> invokeServiceAsync(ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.putOutOfAreaOptionRequest arg0) {
            ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeService inValue = new ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.invokeService();
            inValue.arg0 = arg0;
            return ((ENRLReconSystem.WebAPI.srvAEOutOfAreaOption.PutOutofareaoption)(this)).invokeServiceAsync(inValue);
        }
    }
}
