//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENRLReconSystem.WebAPI.srvAETrrSummary {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class pingHop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string classNameField;
        
        private string bundleNameField;
        
        private string bundleVersionField;
        
        private string bundleIdField;
        
        private string timestampField;
        
        private string applicationAuthorizedField;
        
        private keyValuePair[] configurationInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
                this.RaisePropertyChanged("className");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string bundleName {
            get {
                return this.bundleNameField;
            }
            set {
                this.bundleNameField = value;
                this.RaisePropertyChanged("bundleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string bundleVersion {
            get {
                return this.bundleVersionField;
            }
            set {
                this.bundleVersionField = value;
                this.RaisePropertyChanged("bundleVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string bundleId {
            get {
                return this.bundleIdField;
            }
            set {
                this.bundleIdField = value;
                this.RaisePropertyChanged("bundleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string applicationAuthorized {
            get {
                return this.applicationAuthorizedField;
            }
            set {
                this.applicationAuthorizedField = value;
                this.RaisePropertyChanged("applicationAuthorized");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("configurationInformation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public keyValuePair[] configurationInformation {
            get {
                return this.configurationInformationField;
            }
            set {
                this.configurationInformationField = value;
                this.RaisePropertyChanged("configurationInformation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class keyValuePair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class transactionSummaryType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private contractType contractField;
        
        private string effectiveDateField;
        
        private string medicareClaimNumberField;
        
        private string processDateField;
        
        private transactionCodeType transactionCodeField;
        
        private string transactionDateField;
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public contractType contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
                this.RaisePropertyChanged("contract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string effectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
                this.RaisePropertyChanged("effectiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string medicareClaimNumber {
            get {
                return this.medicareClaimNumberField;
            }
            set {
                this.medicareClaimNumberField = value;
                this.RaisePropertyChanged("medicareClaimNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string processDate {
            get {
                return this.processDateField;
            }
            set {
                this.processDateField = value;
                this.RaisePropertyChanged("processDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public transactionCodeType transactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
                this.RaisePropertyChanged("transactionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("transactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class contractType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contractNumberField;
        
        private string planBenefitPackageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
                this.RaisePropertyChanged("contractNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string planBenefitPackage {
            get {
                return this.planBenefitPackageField;
            }
            set {
                this.planBenefitPackageField = value;
                this.RaisePropertyChanged("planBenefitPackage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class transactionCodeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        private string replyCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string replyCode {
            get {
                return this.replyCodeField;
            }
            set {
                this.replyCodeField = value;
                this.RaisePropertyChanged("replyCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class planCoverageInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string creditableCoverageIndField;
        
        private string eghbIndField;
        
        private string employerSubsidyOverrideIndField;
        
        private string notCoveredMonthsField;
        
        private string partDPremiumAmountField;
        
        private string premiumWitholdOptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string creditableCoverageInd {
            get {
                return this.creditableCoverageIndField;
            }
            set {
                this.creditableCoverageIndField = value;
                this.RaisePropertyChanged("creditableCoverageInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string eghbInd {
            get {
                return this.eghbIndField;
            }
            set {
                this.eghbIndField = value;
                this.RaisePropertyChanged("eghbInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string employerSubsidyOverrideInd {
            get {
                return this.employerSubsidyOverrideIndField;
            }
            set {
                this.employerSubsidyOverrideIndField = value;
                this.RaisePropertyChanged("employerSubsidyOverrideInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string notCoveredMonths {
            get {
                return this.notCoveredMonthsField;
            }
            set {
                this.notCoveredMonthsField = value;
                this.RaisePropertyChanged("notCoveredMonths");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string partDPremiumAmount {
            get {
                return this.partDPremiumAmountField;
            }
            set {
                this.partDPremiumAmountField = value;
                this.RaisePropertyChanged("partDPremiumAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string premiumWitholdOption {
            get {
                return this.premiumWitholdOptionField;
            }
            set {
                this.premiumWitholdOptionField = value;
                this.RaisePropertyChanged("premiumWitholdOption");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class partDGroupInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rxBinField;
        
        private string rxGroupField;
        
        private string rxIdField;
        
        private string rxPcnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rxBin {
            get {
                return this.rxBinField;
            }
            set {
                this.rxBinField = value;
                this.RaisePropertyChanged("rxBin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string rxGroup {
            get {
                return this.rxGroupField;
            }
            set {
                this.rxGroupField = value;
                this.RaisePropertyChanged("rxGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string rxId {
            get {
                return this.rxIdField;
            }
            set {
                this.rxIdField = value;
                this.RaisePropertyChanged("rxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string rxPcn {
            get {
                return this.rxPcnField;
            }
            set {
                this.rxPcnField = value;
                this.RaisePropertyChanged("rxPcn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class transactionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private contractType contractField;
        
        private string effectiveDateField;
        
        private string medicareClaimNumberField;
        
        private partDGroupInfoType partDRxField;
        
        private planCoverageInfoType planCoverageInfoField;
        
        private transactionCodeType transactionCodeField;
        
        private string transactionDateField;
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public contractType contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
                this.RaisePropertyChanged("contract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string effectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
                this.RaisePropertyChanged("effectiveDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string medicareClaimNumber {
            get {
                return this.medicareClaimNumberField;
            }
            set {
                this.medicareClaimNumberField = value;
                this.RaisePropertyChanged("medicareClaimNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public partDGroupInfoType partDRx {
            get {
                return this.partDRxField;
            }
            set {
                this.partDRxField = value;
                this.RaisePropertyChanged("partDRx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public planCoverageInfoType planCoverageInfo {
            get {
                return this.planCoverageInfoField;
            }
            set {
                this.planCoverageInfoField = value;
                this.RaisePropertyChanged("planCoverageInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public transactionCodeType transactionCode {
            get {
                return this.transactionCodeField;
            }
            set {
                this.transactionCodeField = value;
                this.RaisePropertyChanged("transactionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("transactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class trrsummary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private transactionType[] badHistoryTransactionField;
        
        private transactionType[] badPendingTransactionField;
        
        private transactionSummaryType[] summaryTransactionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("badHistoryTransaction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public transactionType[] badHistoryTransaction {
            get {
                return this.badHistoryTransactionField;
            }
            set {
                this.badHistoryTransactionField = value;
                this.RaisePropertyChanged("badHistoryTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("badPendingTransaction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public transactionType[] badPendingTransaction {
            get {
                return this.badPendingTransactionField;
            }
            set {
                this.badPendingTransactionField = value;
                this.RaisePropertyChanged("badPendingTransaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("summaryTransaction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public transactionSummaryType[] summaryTransaction {
            get {
                return this.summaryTransactionField;
            }
            set {
                this.summaryTransactionField = value;
                this.RaisePropertyChanged("summaryTransaction");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class vr1StatusContainer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vr1_status_additional_infoField;
        
        private string vr1_status_codeField;
        
        private string vr1_status_code_descField;
        
        private string vr1_status_code_type_descField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string vr1_status_additional_info {
            get {
                return this.vr1_status_additional_infoField;
            }
            set {
                this.vr1_status_additional_infoField = value;
                this.RaisePropertyChanged("vr1_status_additional_info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vr1_status_code {
            get {
                return this.vr1_status_codeField;
            }
            set {
                this.vr1_status_codeField = value;
                this.RaisePropertyChanged("vr1_status_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string vr1_status_code_desc {
            get {
                return this.vr1_status_code_descField;
            }
            set {
                this.vr1_status_code_descField = value;
                this.RaisePropertyChanged("vr1_status_code_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string vr1_status_code_type_desc {
            get {
                return this.vr1_status_code_type_descField;
            }
            set {
                this.vr1_status_code_type_descField = value;
                this.RaisePropertyChanged("vr1_status_code_type_desc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class vrcStatusGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private vr1StatusContainer[] statusContainerBeansField;
        
        private string vr1_status_container_num_occField;
        
        private string vrc_status_generated_byField;
        
        private string vrc_status_orig_channelField;
        
        private string vrc_status_owned_byField;
        
        private string vrc_status_service_nameField;
        
        private string vrc_status_service_versionField;
        
        private string vrc_status_systemField;
        
        private string vrc_status_transidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("statusContainerBeans", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public vr1StatusContainer[] statusContainerBeans {
            get {
                return this.statusContainerBeansField;
            }
            set {
                this.statusContainerBeansField = value;
                this.RaisePropertyChanged("statusContainerBeans");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vr1_status_container_num_occ {
            get {
                return this.vr1_status_container_num_occField;
            }
            set {
                this.vr1_status_container_num_occField = value;
                this.RaisePropertyChanged("vr1_status_container_num_occ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string vrc_status_generated_by {
            get {
                return this.vrc_status_generated_byField;
            }
            set {
                this.vrc_status_generated_byField = value;
                this.RaisePropertyChanged("vrc_status_generated_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string vrc_status_orig_channel {
            get {
                return this.vrc_status_orig_channelField;
            }
            set {
                this.vrc_status_orig_channelField = value;
                this.RaisePropertyChanged("vrc_status_orig_channel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string vrc_status_owned_by {
            get {
                return this.vrc_status_owned_byField;
            }
            set {
                this.vrc_status_owned_byField = value;
                this.RaisePropertyChanged("vrc_status_owned_by");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string vrc_status_service_name {
            get {
                return this.vrc_status_service_nameField;
            }
            set {
                this.vrc_status_service_nameField = value;
                this.RaisePropertyChanged("vrc_status_service_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string vrc_status_service_version {
            get {
                return this.vrc_status_service_versionField;
            }
            set {
                this.vrc_status_service_versionField = value;
                this.RaisePropertyChanged("vrc_status_service_version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string vrc_status_system {
            get {
                return this.vrc_status_systemField;
            }
            set {
                this.vrc_status_systemField = value;
                this.RaisePropertyChanged("vrc_status_system");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string vrc_status_transid {
            get {
                return this.vrc_status_transidField;
            }
            set {
                this.vrc_status_transidField = value;
                this.RaisePropertyChanged("vrc_status_transid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class statusMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private statusMessageLevel statusMessageLevelField;
        
        private string messageTypeField;
        
        private string statusMessage1Field;
        
        private string hopLocationField;
        
        private string stackTraceField;
        
        private string statusOriginField;
        
        private vrcStatusGroup vrcStatusGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public statusMessageLevel statusMessageLevel {
            get {
                return this.statusMessageLevelField;
            }
            set {
                this.statusMessageLevelField = value;
                this.RaisePropertyChanged("statusMessageLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string messageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("messageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("statusMessage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statusMessage1 {
            get {
                return this.statusMessage1Field;
            }
            set {
                this.statusMessage1Field = value;
                this.RaisePropertyChanged("statusMessage1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string hopLocation {
            get {
                return this.hopLocationField;
            }
            set {
                this.hopLocationField = value;
                this.RaisePropertyChanged("hopLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string statusOrigin {
            get {
                return this.statusOriginField;
            }
            set {
                this.statusOriginField = value;
                this.RaisePropertyChanged("statusOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public vrcStatusGroup vrcStatusGroup {
            get {
                return this.vrcStatusGroupField;
            }
            set {
                this.vrcStatusGroupField = value;
                this.RaisePropertyChanged("vrcStatusGroup");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public enum statusMessageLevel {
        
        /// <remarks/>
        INFORMATIONAL,
        
        /// <remarks/>
        FAULT,
        
        /// <remarks/>
        EXCEPTION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class serviceHop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bundleNameField;
        
        private string bundleVersionField;
        
        private string bundleIdField;
        
        private string startTimestampField;
        
        private string endTimestampField;
        
        private string totalTimeInMillisecondsField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bundleName {
            get {
                return this.bundleNameField;
            }
            set {
                this.bundleNameField = value;
                this.RaisePropertyChanged("bundleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string bundleVersion {
            get {
                return this.bundleVersionField;
            }
            set {
                this.bundleVersionField = value;
                this.RaisePropertyChanged("bundleVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string bundleId {
            get {
                return this.bundleIdField;
            }
            set {
                this.bundleIdField = value;
                this.RaisePropertyChanged("bundleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string startTimestamp {
            get {
                return this.startTimestampField;
            }
            set {
                this.startTimestampField = value;
                this.RaisePropertyChanged("startTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string endTimestamp {
            get {
                return this.endTimestampField;
            }
            set {
                this.endTimestampField = value;
                this.RaisePropertyChanged("endTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string totalTimeInMilliseconds {
            get {
                return this.totalTimeInMillisecondsField;
            }
            set {
                this.totalTimeInMillisecondsField = value;
                this.RaisePropertyChanged("totalTimeInMilliseconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class responseHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private serviceCallStatus serviceCallStatusField;
        
        private string externalIdField;
        
        private string serviceNameField;
        
        private string serviceVersionField;
        
        private logLevel logLevelField;
        
        private string upmEnvironmentField;
        
        private serviceHop[] serviceHopsField;
        
        private statusMessage[] statusMessagesField;
        
        private internalUse internalUseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public serviceCallStatus serviceCallStatus {
            get {
                return this.serviceCallStatusField;
            }
            set {
                this.serviceCallStatusField = value;
                this.RaisePropertyChanged("serviceCallStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string externalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
                this.RaisePropertyChanged("externalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("serviceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string serviceVersion {
            get {
                return this.serviceVersionField;
            }
            set {
                this.serviceVersionField = value;
                this.RaisePropertyChanged("serviceVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public logLevel logLevel {
            get {
                return this.logLevelField;
            }
            set {
                this.logLevelField = value;
                this.RaisePropertyChanged("logLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string upmEnvironment {
            get {
                return this.upmEnvironmentField;
            }
            set {
                this.upmEnvironmentField = value;
                this.RaisePropertyChanged("upmEnvironment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceHops", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public serviceHop[] serviceHops {
            get {
                return this.serviceHopsField;
            }
            set {
                this.serviceHopsField = value;
                this.RaisePropertyChanged("serviceHops");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("statusMessages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public statusMessage[] statusMessages {
            get {
                return this.statusMessagesField;
            }
            set {
                this.statusMessagesField = value;
                this.RaisePropertyChanged("statusMessages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public internalUse internalUse {
            get {
                return this.internalUseField;
            }
            set {
                this.internalUseField = value;
                this.RaisePropertyChanged("internalUse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public enum serviceCallStatus {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        INFO,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        EXCEPTION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public enum logLevel {
        
        /// <remarks/>
        DEFAULT,
        
        /// <remarks/>
        TRACE,
        
        /// <remarks/>
        DEBUG,
        
        /// <remarks/>
        INFO,
        
        /// <remarks/>
        WARN,
        
        /// <remarks/>
        ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class internalUse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uidField;
        
        private string serviceNameField;
        
        private string serviceVersionField;
        
        private string originalConsumerField;
        
        private string originalServiceNameField;
        
        private string originalServiceVersionField;
        
        private System.Nullable<int> logSequenceField;
        
        private string uidGeneratedByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("serviceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string serviceVersion {
            get {
                return this.serviceVersionField;
            }
            set {
                this.serviceVersionField = value;
                this.RaisePropertyChanged("serviceVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string originalConsumer {
            get {
                return this.originalConsumerField;
            }
            set {
                this.originalConsumerField = value;
                this.RaisePropertyChanged("originalConsumer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string originalServiceName {
            get {
                return this.originalServiceNameField;
            }
            set {
                this.originalServiceNameField = value;
                this.RaisePropertyChanged("originalServiceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string originalServiceVersion {
            get {
                return this.originalServiceVersionField;
            }
            set {
                this.originalServiceVersionField = value;
                this.RaisePropertyChanged("originalServiceVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<int> logSequence {
            get {
                return this.logSequenceField;
            }
            set {
                this.logSequenceField = value;
                this.RaisePropertyChanged("logSequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string uidGeneratedBy {
            get {
                return this.uidGeneratedByField;
            }
            set {
                this.uidGeneratedByField = value;
                this.RaisePropertyChanged("uidGeneratedBy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(pingResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(responseBase2))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(searchTrrSummaryResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public abstract partial class responseBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private responseHeader responseHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public responseHeader responseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
                this.RaisePropertyChanged("responseHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class pingResponse : responseBase {
        
        private pingHop[] pingHopsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pingHops", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public pingHop[] pingHops {
            get {
                return this.pingHopsField;
            }
            set {
                this.pingHopsField = value;
                this.RaisePropertyChanged("pingHops");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(searchTrrSummaryResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class responseBase2 : responseBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class searchTrrSummaryResponse : responseBase2 {
        
        private trrsummary trrsummaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public trrsummary trrsummary {
            get {
                return this.trrsummaryField;
            }
            set {
                this.trrsummaryField = value;
                this.RaisePropertyChanged("trrsummary");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class gpsSystemParametersType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientIdField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("clientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class controlModifiersType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gpsSystemParametersType gpsSystemParametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gpsSystemParametersType gpsSystemParameters {
            get {
                return this.gpsSystemParametersField;
            }
            set {
                this.gpsSystemParametersField = value;
                this.RaisePropertyChanged("gpsSystemParameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class requestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string applicationNameField;
        
        private string applicationInstanceNameField;
        
        private logLevel logLevelField;
        
        private string externalIdField;
        
        private keyValuePair[] serviceOptionField;
        
        private internalUse internalUseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string applicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
                this.RaisePropertyChanged("applicationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string applicationInstanceName {
            get {
                return this.applicationInstanceNameField;
            }
            set {
                this.applicationInstanceNameField = value;
                this.RaisePropertyChanged("applicationInstanceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public logLevel logLevel {
            get {
                return this.logLevelField;
            }
            set {
                this.logLevelField = value;
                this.RaisePropertyChanged("logLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string externalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
                this.RaisePropertyChanged("externalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceOption", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public keyValuePair[] serviceOption {
            get {
                return this.serviceOptionField;
            }
            set {
                this.serviceOptionField = value;
                this.RaisePropertyChanged("serviceOption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public internalUse internalUse {
            get {
                return this.internalUseField;
            }
            set {
                this.internalUseField = value;
                this.RaisePropertyChanged("internalUse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(pingRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(searchTrrSummaryRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public abstract partial class requestBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private requestHeader requestHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public requestHeader requestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("requestHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com")]
    public partial class pingRequest : requestBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class searchTrrSummaryRequest : requestBase {
        
        private searchTrrSummaryRequestSearch searchField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public searchTrrSummaryRequestSearch search {
            get {
                return this.searchField;
            }
            set {
                this.searchField = value;
                this.RaisePropertyChanged("search");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1")]
    public partial class searchTrrSummaryRequestSearch : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string individualIdField;
        
        private controlModifiersType controlModifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string individualId {
            get {
                return this.individualIdField;
            }
            set {
                this.individualIdField = value;
                this.RaisePropertyChanged("individualId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public controlModifiersType controlModifier {
            get {
                return this.controlModifierField;
            }
            set {
                this.controlModifierField = value;
                this.RaisePropertyChanged("controlModifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1", ConfigurationName="srvAETrrSummary.SearchTrrSummary")]
    public interface SearchTrrSummary {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ENRLReconSystem.WebAPI.srvAETrrSummary.ServiceException), Action="", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ENRLReconSystem.WebAPI.srvAETrrSummary.invokePingResponse invokePing(ENRLReconSystem.WebAPI.srvAETrrSummary.invokePing request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ENRLReconSystem.WebAPI.srvAETrrSummary.invokePingResponse> invokePingAsync(ENRLReconSystem.WebAPI.srvAETrrSummary.invokePing request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ENRLReconSystem.WebAPI.srvAETrrSummary.ServiceException), Action="", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(responseBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(requestBase))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ENRLReconSystem.WebAPI.srvAETrrSummary.invokeServiceResponse invokeService(ENRLReconSystem.WebAPI.srvAETrrSummary.invokeService request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ENRLReconSystem.WebAPI.srvAETrrSummary.invokeServiceResponse> invokeServiceAsync(ENRLReconSystem.WebAPI.srvAETrrSummary.invokeService request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokePing", WrapperNamespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1", IsWrapped=true)]
    public partial class invokePing {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ENRLReconSystem.WebAPI.srvAETrrSummary.pingRequest arg0;
        
        public invokePing() {
        }
        
        public invokePing(ENRLReconSystem.WebAPI.srvAETrrSummary.pingRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokePingResponse", WrapperNamespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1", IsWrapped=true)]
    public partial class invokePingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ENRLReconSystem.WebAPI.srvAETrrSummary.pingResponse @return;
        
        public invokePingResponse() {
        }
        
        public invokePingResponse(ENRLReconSystem.WebAPI.srvAETrrSummary.pingResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokeService", WrapperNamespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1", IsWrapped=true)]
    public partial class invokeService {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ENRLReconSystem.WebAPI.srvAETrrSummary.searchTrrSummaryRequest arg0;
        
        public invokeService() {
        }
        
        public invokeService(ENRLReconSystem.WebAPI.srvAETrrSummary.searchTrrSummaryRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="invokeServiceResponse", WrapperNamespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1", IsWrapped=true)]
    public partial class invokeServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://upm3.uhc.com/uhcmr/cms/trrsummary/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ENRLReconSystem.WebAPI.srvAETrrSummary.searchTrrSummaryResponse @return;
        
        public invokeServiceResponse() {
        }
        
        public invokeServiceResponse(ENRLReconSystem.WebAPI.srvAETrrSummary.searchTrrSummaryResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchTrrSummaryChannel : ENRLReconSystem.WebAPI.srvAETrrSummary.SearchTrrSummary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchTrrSummaryClient : System.ServiceModel.ClientBase<ENRLReconSystem.WebAPI.srvAETrrSummary.SearchTrrSummary>, ENRLReconSystem.WebAPI.srvAETrrSummary.SearchTrrSummary {
        
        public SearchTrrSummaryClient() {
        }
        
        public SearchTrrSummaryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchTrrSummaryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchTrrSummaryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchTrrSummaryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ENRLReconSystem.WebAPI.srvAETrrSummary.invokePingResponse ENRLReconSystem.WebAPI.srvAETrrSummary.SearchTrrSummary.invokePing(ENRLReconSystem.WebAPI.srvAETrrSummary.invokePing request) {
            return base.Channel.invokePing(request);
        }
        
        public ENRLReconSystem.WebAPI.srvAETrrSummary.pingResponse invokePing(ENRLReconSystem.WebAPI.srvAETrrSummary.pingRequest arg0) {
            ENRLReconSystem.WebAPI.srvAETrrSummary.invokePing inValue = new ENRLReconSystem.WebAPI.srvAETrrSummary.invokePing();
            inValue.arg0 = arg0;
            ENRLReconSystem.WebAPI.srvAETrrSummary.invokePingResponse retVal = ((ENRLReconSystem.WebAPI.srvAETrrSummary.SearchTrrSummary)(this)).invokePing(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ENRLReconSystem.WebAPI.srvAETrrSummary.invokePingResponse> ENRLReconSystem.WebAPI.srvAETrrSummary.SearchTrrSummary.invokePingAsync(ENRLReconSystem.WebAPI.srvAETrrSummary.invokePing request) {
            return base.Channel.invokePingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ENRLReconSystem.WebAPI.srvAETrrSummary.invokePingResponse> invokePingAsync(ENRLReconSystem.WebAPI.srvAETrrSummary.pingRequest arg0) {
            ENRLReconSystem.WebAPI.srvAETrrSummary.invokePing inValue = new ENRLReconSystem.WebAPI.srvAETrrSummary.invokePing();
            inValue.arg0 = arg0;
            return ((ENRLReconSystem.WebAPI.srvAETrrSummary.SearchTrrSummary)(this)).invokePingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ENRLReconSystem.WebAPI.srvAETrrSummary.invokeServiceResponse ENRLReconSystem.WebAPI.srvAETrrSummary.SearchTrrSummary.invokeService(ENRLReconSystem.WebAPI.srvAETrrSummary.invokeService request) {
            return base.Channel.invokeService(request);
        }
        
        public ENRLReconSystem.WebAPI.srvAETrrSummary.searchTrrSummaryResponse invokeService(ENRLReconSystem.WebAPI.srvAETrrSummary.searchTrrSummaryRequest arg0) {
            ENRLReconSystem.WebAPI.srvAETrrSummary.invokeService inValue = new ENRLReconSystem.WebAPI.srvAETrrSummary.invokeService();
            inValue.arg0 = arg0;
            ENRLReconSystem.WebAPI.srvAETrrSummary.invokeServiceResponse retVal = ((ENRLReconSystem.WebAPI.srvAETrrSummary.SearchTrrSummary)(this)).invokeService(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ENRLReconSystem.WebAPI.srvAETrrSummary.invokeServiceResponse> ENRLReconSystem.WebAPI.srvAETrrSummary.SearchTrrSummary.invokeServiceAsync(ENRLReconSystem.WebAPI.srvAETrrSummary.invokeService request) {
            return base.Channel.invokeServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ENRLReconSystem.WebAPI.srvAETrrSummary.invokeServiceResponse> invokeServiceAsync(ENRLReconSystem.WebAPI.srvAETrrSummary.searchTrrSummaryRequest arg0) {
            ENRLReconSystem.WebAPI.srvAETrrSummary.invokeService inValue = new ENRLReconSystem.WebAPI.srvAETrrSummary.invokeService();
            inValue.arg0 = arg0;
            return ((ENRLReconSystem.WebAPI.srvAETrrSummary.SearchTrrSummary)(this)).invokeServiceAsync(inValue);
        }
    }
}
